### PR TITLE
add slack signup  /api/slack

### PR DESCRIPTION
**Pull request by lunky**
#18

### CODE REVIEW

**Comment by lunky** [comment]
reopen

**Comment by lunky** [comment]
removed exception throwing

**Comment by amirci** [comment]
I think the `web.config` doesn't need to change because the env vars are set in Azure, etc.
The `build.fsx` file has still a reference to `wpgdotnet.fsx`. 
Don't think we need the custom error handler for now, so we could reset the changes on `build.fsx`.

**Comment by lunky** [comment]
reverted build.fsx, web.config

**Comment by amirci** [comment]
Already merged

**Pull request closed without merging**
